development:
  sessions:
    default:
      database: apidoc_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: apidoc_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: apidoc
      hosts:
        - localhost:27017
